# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json

language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  high_level_summary_instructions: 'Create concise release notes as a bullet-point list, followed by a Markdown table showing lines added and removed by each contributing author.'
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: |
    Use the Conventional Commits format for PR titles.
    Format: <type>(<scope>): <short imperative description>
    - type must be one of: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
    - scope is optional but recommended (e.g., admin, api, user, db)
    - description must be brief, imperative, and lowercase
    - no trailing period
    Example: feat(admin): decrypt user email and phone before user event
  review_status: false
  full_review: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: true
  labeling_instructions: []
  base_branches: # allow auto-reviews on these target branches
    - master
    - develop
    - staging
    - feature/*

  #Exclude non-source code directories from reviews.
  path_filters:
    - '!deployment/**'
    - '!dev-ops/**'
    - '!release-notes/**'
    - '!src/api-doc/**'
    - '!src/assets/**'
    - '!src/configs/**'
    - '!src/public/**'
    - '!src/temp/**'
    - '!**/*.md'

  # Add specific review instructions for critical paths.
  path_instructions:
    - path: 'src/services/**'
      instructions: 'This is core business logic. Please check for correctness, efficiency, and potential edge cases.'
    - path: 'src/controllers/**'
      instructions: 'These are API controllers. Focus on request/response handling, security (auth middleware usage), and proper status codes.'
    - path: 'src/database/queries/**'
      instructions: 'Review database queries for performance. Check for N+1 problems and ensure indexes can be used.'
    - path: 'src/validators/**'
      instructions: 'Validate all incoming data thoroughly. Check for missing or incomplete validation rules.'
    - path: 'src/middlewares/**'
      instructions: 'This is security-sensitive middleware. Scrutinize for potential vulnerabilities.'

  abort_on_close: true
  disable_cache: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: ['WIP', 'skip-review']
    labels: []
    drafts: false
    # Target reviews to development branches.
    base_branches:
      - 'develop'

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  pre_merge_checks:
    docstrings:
      mode: warning
      threshold: 80
    title:
      mode: warning
      requirements: ''
    description:
      mode: warning
    issue_assessment:
      mode: warning
  tools:
    osvScanner:
      enabled: true
    eslint:
      enabled: true
    semgrep:
      enabled: true
    dotenvLint:
      enabled: true
    sqlfluff:
      enabled: true
    checkov:
      enabled: true
    gitleaks:
      enabled: true
    hadolint:
      enabled: true
    shellcheck:
      enabled: true
    actionlint:
      enabled: true
    circleci:
      enabled: true
    github-checks:
      enabled: true
    markdownlint:
      enabled: true
    yamllint:
      enabled: true
    biome:
      enabled: true
    languagetool:
      enabled: false # optional
    ast-grep:
      essential_rules: true
      rule_dirs: []
      util_dirs: []
      packages: []
chat:
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto
code_generation:
  docstrings:
    language: en-US
    path_instructions: []
  unit_tests:
    path_instructions: []
